### ISSUE TITLE
Prevent `iconsClassesGenerator.js` from failing if icons aren't found

### ISSUE THREAD

**Issue by julien** [liferay/liferay-ckeditor#123]
The [`iconsClassesGenerator.js`](https://github.com/liferay/liferay-ckeditor/blob/20e6ce2c1849e213be42664bf2a5523f73d87b86/support/iconsClassesGenerator.js) script [reads](https://github.com/liferay/liferay-ckeditor/blob/20e6ce2c1849e213be42664bf2a5523f73d87b86/support/iconsClassesGenerator.js#L106-L126) files but if these files are non existent it will crash and prevent the build script from generating the `ckeditor` bundle.

Here's how to make it crash:

- Edit [icons.json](https://github.com/liferay/liferay-ckeditor/blob/20e6ce2c1849e213be42664bf2a5523f73d87b86/skins/moono-lexicon/icons/icons.json) and add a new "entry" to the `icons` object, for example 

    ```json
    ...
    icons: {
       "preview": "preview"
    }
    ...
    ```

- Build `ckeditor` with 

    ```sh
    ./ck.sh build
    ```

- See it fail with the following message:

    ```js
    fs.js:115
        throw err;
        ^

    Error: ENOENT: no such file or directory, open '../node_modules/@clayui/css/lib/images/icons/preview.svg'
        at Object.openSync (fs.js:439:3)
        at Object.readFileSync (fs.js:344:35)
        at Object.<anonymous> (/home/jc/Documents/liferay-ckeditor/support/iconsClassesGenerator.js:106:22)
        at Module._compile (internal/modules/cjs/loader.js:689:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
        at Module.load (internal/modules/cjs/loader.js:599:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
        at Function.Module._load (internal/modules/cjs/loader.js:530:3)
        at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
        at startup (internal/bootstrap/node.js:283:19)
    ```

**Comment by julien** [comment]
Fixed by #124
